spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: fengjutian
  data:
    neo4j:
      database: neo4j  # 如果你指定了其他数据库名，改这里


#springdoc:
#  api-docs:
#    path: /api-docs-json # 更改 JSON 文档的路径
#  swagger-ui:
#    path: /swagger-ui # 更改 Swagger UI 的路径
#    tags-sorter: alpha # 按字母顺序对标签进行排序
#    operations-sorter: method # 按 HTTP 方法排序
#  pathsToMatch: # 只生成特定路径的文档
#    - /api/**